model_class: 'SCConformerXL'

model:
  feat_in: 80
  n_layers: 6
  d_model: 768
  n_heads: 6
  head_dim: 128
  use_rotary: true
  rotary_base_freq: 1500000
  self_conditioning: false
  subsampling_factor: 8
  subsampling: 'dw_striding'
  subsampling_act: 'silu'
  subsampling_conv_channels: 256
  ctc_loss_weight: 0.05
  acoustic_norm: false
  flash_attn: true

optimizer:
  name: madgrad
  args:
    lr: 1e-4

scheduler:
  warmup_steps: 100

audio_chunking:
  size: 2048
  overlap: 0

sequence_scheduler:
  increase_every: 5000        # 5000ステップごとに伸ばす
  stop_after: 90000           # 9万ステップで停止
  start_after: 0
  max_sequence_length: 16384  # 目標コンテキスト長（例: 2.7分）
  increase_by_multiplier: 2
  batch_size_multiplier: 0.5  # chunkが2倍→batchを半分に

wandb:
  use: false
  project_name: earnings22_enc_dec
  name: earnings22_ft_smoke
  update_config_with_wandb_id: false
  id: ''

checkpointing:
  dir: /home/t23cs033/long-context-asr/data/earnings22/checkpoints
  # pretrained: /home/t23cs033/long-context-asr/checkpoints/pretrained/n_seq_sched_1024_rp_1/step_105360.pt
  save_every_n_steps: 1000

data:
  path: /home/t23cs033/long-context-asr/data/earnings22/manifest.json

training:
  start_spec_augment_after_n_epochs: -1
  max_epochs: 12
  batch_size: 22
  backprop_every: 4
  backwards_every: 1
  max_seq_len: 0
  clip_value: 0.8
  intermediate_loss_weighting: 0.0
  random_seed: 552268
  dtype: bfloat16
